# fly.your-nest-app.toml configuration file
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

# TODO: Match the fly app name
app = "tawasul-api"
primary_region = 'nrt'

[build]
dockerfile = "./apps/api/Dockerfile"

[build.args]
# TODO: Match the workspace app name
WORKSPACE_APP = "api"

# api_gateway
[http_service]
internal_port = 1337
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0

processes = ["app"]